### ISSUE TITLE
Doesn't show up

### ISSUE THREAD

**Issue by Zharkan** [ef2-digital/strapi-plugin-bold-title-editor#1]
Plugin doesn't show in content manager, the field shows "Not supported" instead. Am I missing something ?

Using Strapi V4.5.3.

**Comment by Zharkan** [comment]
So  it actually works but only when it's not used within components.

**Comment by bartkoelewijnnl** [comment]
Hi @Zharkan, it should also work with components. Can you share a screenshot of your component and the error message?

**Comment by Zharkan** [comment]
Hi, yes of course, the custom field is the "Not supported" one.
![ksnip_20221213-224605](https://user-images.githubusercontent.com/53452535/207450886-070ba4ba-ff0c-4ebc-9047-5ecdb28b1d6b.png)

**Comment by bartkoelewijnnl** [comment]
@Zharkan It's a common issue in Strapi 4.5.3 https://github.com/strapi/strapi/issues/15053. Version 4.5.4 solves your issue https://github.com/strapi/strapi/pull/15067.
