### ISSUE TITLE
Option to return markdown instead HTML

### ISSUE THREAD

**Issue by sapkra** [ef2-digital/strapi-plugin-bold-title-editor#2]
I really like your plugin but it would be great if there would be an option to return markdown instead HTML because the default markdown editor of Strapi is way too large for titles.

**Comment by bartkoelewijnnl** [comment]
Hi, I added a markdown output option for the plugin. For now in beta (`@ef2/strapi-plugin-bold-title-editor@1.0.7-beta.4`). When you add the custom field, you can choose the output "HTML" or "Markdown".

**Comment by sapkra** [comment]
Thank you for implementing it that quickly. 🚀 Sounds great, I will try it out within the upcoming two weeks.

**Comment by sapkra** [comment]
Building strapi is crashing because the plugin uses a different react version than strapi. Strapi is not yet on React 18.

**Comment by bartkoelewijnnl** [comment]
You're right. The react dependency was there only for testing and is now removed, version `1.0.7` is now released

**Comment by sapkra** [comment]
Maybe some docs about this new feature should be added to the README.md. ;D

**Comment by bartkoelewijnnl** [comment]
I have updated the docs now 😉
