### ISSUE TITLE
Cannot "unassign" value (set an empty value)

### ISSUE THREAD

**Issue by DaDlugosch** [ef2-digital/strapi-plugin-bold-title-editor#3]
If I want to remove previously set value (save an empty value), I cannot do that. After click on "Save" button, the old text always come back (so the new value - empty value - is not saved). In the case of changing value to something else (eg. from "Test" to "Test1"), rewriting works properly.

**Comment by bartkoelewijnnl** [comment]
Hi @DaDlugosch, thank you for your message. Which version are you using? Do you also get this error with version `1.0.7`?

**Comment by DaDlugosch** [comment]
I have got this issue in version `1.0.6`, however now, I'm using version `1.0.7`, but the issue appears to be somewhere else. When I "unassign" value, I've got `<br>` in the API response. But I expect to get empty string, not a `<br>`.

**Comment by bartkoelewijnnl** [comment]
Hi @DaDlugosch, version 1.0.8 is now released and solves your issue. If `<br>` is already saved for a field in the database, you need to save again to see the right effects.
